### ISSUE TITLE
Api and Web UI

### ISSUE THREAD

**Issue by robitmoh** [mixerapi/crud#1]
Hi
I need help, to the CRUD plugin

My app has a API (in ApiV1 prefix in app) and Web Ui 

If I load the CRUD plugin in Application.php, the pugin block the WebUI method like the "add"
In the WEB UI "add" use GET and POST method, in the CRUD only the POST.
I set with the $options to empty allowedMethods
But I want to set the original CRUD rules if the request use the ApiV1 prefix
like the ApController
 if($this->request->getParam('prefix') == 'Apiv1') { ...... }
 
 Can you write some help, example?
Regards Robit

**Comment by cnizzardini** [comment]
Sorry for my belated response. I am not sure I fully understand the issue being experienced here. Are you still having these issues?

**Comment by robitmoh** [comment]
Hi
Thanks your reply.
Yes I have the issue, but not a big problem at this developing time.

The plugins must to load in Application.php bootstrap method and the default restricts block the standard CakePHP add function,
because that use GET and POST methodes
But I don't know how can I change the alowedMethods[] later 
for example in the AppController.php.
I want set different restricts per prefixes 
In the Api prefix, the  add method only the POST allowed
In the root prefix (/) like standard cakephp web UI add function use GET and POST

Robit

**Comment by cnizzardini** [comment]
Please add future issues to here: https://github.com/mixerapi/mixerapi-dev
